---
# vars file for roles/create_vm_windows_azure
 # vars: 
  myResourceGroup: Lab_DevOps
  vars_prompt:
    - name: azure_user 
      prompt: "Enter local administrator "
    - name: password
      prompt: "Enter local administrator password"
      
...
