---
# tasks file for create_vm_azure
  - name: Create Resource Group
    azure_rm_resourcegroup:
      name: "{{ myResourceGroup }}"
      location: "Brazil South"

  - name: Create Network Security Group
    azure_rm_securitygroup:
      resource_group: "{{ myResourceGroup }}"
      name: networkSecurityGroup
      rules:
        - name: 'allow_rdp'
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound
        - name: 'allow_web_traffic'
          protocol: Tcp
          destination_port_range:
            - 80
            - 443
          access: Allow
          priority: 1002
          direction: Inbound
        - name: 'allow_powershell_remoting'
          protocol: Tcp
          destination_port_range: 
            - 5985
            - 5986
          access: Allow
          priority: 1003
          direction: Inbound

  - name: Create a network interface
    azure_rm_networkinterface:
      name: nic
      location: "Brazil South"
      resource_group: "{{ myResourceGroup }}"
      virtual_network: vNet-Lab-DevOS
      subnet_name: subNet-1-Lab-DevOps 
      security_group: networkSecurityGroup
      ip_configurations:
        - name: default
          public_ip_address_name: pip
          primary: True


  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group:  "{{ myResourceGroup }}"
      allocation_method: Static
      name: pip
    register: output_ip_address

  - name: Output public IP
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}"


  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ myResourceGroup }}"
      name: win-vm
      vm_size: Standard_DS1_v2
      admin_username: "{{ azure_user }}"
      admin_password: "{{ password }}"
      network_interfaces: nic
      os_type: Windows
      image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2019-Datacenter
          version: latest
   # no_log: true
...
